export const FETCH_INSTRUMENT = 'FETCH_INSTRUMENT';
export const RECEIVE_INSTRUMENT = 'RECEIVE_INSTRUMENT';

export const FETCH_READ_CSV = 'FETCH_READ_CSV';
export const RECEIVE_READ_CSV = 'RECEIVE_READ_CSV';

export const FETCH_READ_PRICE = 'FETCH_READ_PRICE';
export const RECEIVE_READ_PRICE = 'RECEIVE_READ_PRICE';

export const FETCH_DEALING = 'FETCH_DEALING';
export const RECEIVE_DEALING = 'RECEIVE_DEALING';

export const FETCH_ACD = 'FETCH_ACD';
export const RECEIVE_ACD = 'RECEIVE_ACD';

export const MONEY_REQUEST = 'MONEY_REQUEST';
export const MONEY_SUCCESS = 'MONEY_SUCCESS';
export const MONEY_FAILURE = 'MONEY_FAILURE';

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_ACD_TODAY = 'FETCH_ACD_TODAY';
export const RECEIVE_ACD_TODAY = 'RECEIVE_ACD_TODAY';

export const FETCH_ACD_NEXT= 'FETCH_ACD_NEXT';
export const RECEIVE_ACD_NEXT = 'RECEIVE_ACD_NEXT';

export const FETCH_ACD_PREVIOUS = 'FETCH_ACD_PREVIOUS';
export const RECEIVE_ACD_PREVIOUS = 'RECEIVE_ACD_PREVIOUS';

export const FETCH_ACD_DATA = 'FETCH_ACD_DATA';
export const RECEIVE_ACD_DATA = 'RECEIVE_ACD_DATA';

export const FETCH_ACDINSTRUMENT_DATA = 'FETCH_ACDINSTRUMENT_DATA';
export const RECEIVE_ACDINSTRUMENT_DATA = 'RECEIVE_ACDINSTRUMENT_DATA';

export const FETCH_ACDACCOUNT_DATA = 'FETCH_ACDACCOUNT_DATA';
export const RECEIVE_ACDACCOUNT_DATA = 'RECEIVE_ACDACCOUNT_DATA';

export const FETCH_ACDDEAL_DATA = 'FETCH_ACDDEAL_DATA';
export const RECEIVE_ACDDEAL_DATA = 'RECEIVE_ACDDEAL_DATA';
