export const FETCH_DEALING = 'FETCH_DEALING';
export const RECEIVE_DEALING = 'RECEIVE_DEALING';

export const FETCH_DEALINGBYBOXDATE = 'FETCH_DEALINGBYBOXDATE';
export const RECEIVE_DEALINGBYBOXDATE = 'RECEIVE_DEALINGBYBOXDATE';


export const FETCH_ACD = 'FETCH_ACD';
export const RECEIVE_ACD = 'RECEIVE_ACD';

export const MONEY_REQUEST = 'MONEY_REQUEST';
export const MONEY_SUCCESS = 'MONEY_SUCCESS';
export const MONEY_FAILURE = 'MONEY_FAILURE';

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_ACD_TODAY = 'FETCH_ACD_TODAY';
export const RECEIVE_ACD_TODAY = 'RECEIVE_ACD_TODAY';

export const FETCH_ACD_NEXT= 'FETCH_ACD_NEXT';
export const RECEIVE_ACD_NEXT = 'RECEIVE_ACD_NEXT';

export const FETCH_ACD_PREVIOUS = 'FETCH_ACD_PREVIOUS';
export const RECEIVE_ACD_PREVIOUS = 'RECEIVE_ACD_PREVIOUS';

export const FETCH_ACD_DATA = 'FETCH_ACD_DATA';
export const RECEIVE_ACD_DATA = 'RECEIVE_ACD_DATA';

export const FETCH_ACDINSTRUMENT_DATA = 'FETCH_ACDINSTRUMENT_DATA';
export const RECEIVE_ACDINSTRUMENT_DATA = 'RECEIVE_ACDINSTRUMENT_DATA';

export const FETCH_ACDACCOUNT_DATA = 'FETCH_ACDACCOUNT_DATA';
export const RECEIVE_ACDACCOUNT_DATA = 'RECEIVE_ACDACCOUNT_DATA';

export const FETCH_POSTACDACCOUNT_DATA = 'FETCH_POSTACDACCOUNT_DATA';
export const POST_ACDACCOUNT_DATA = 'POST_ACDACCOUNT_DATA';

export const FETCH_ACDDEAL_DATA = 'FETCH_ACDDEAL_DATA';
export const RECEIVE_ACDDEAL_DATA = 'RECEIVE_ACDDEAL_DATA';

export const FETCH_POSTACD_DATA = 'FETCH_POSTACD_DATA';
export const POST_ACD_DATA = 'POST_ACD_DATA';

export const FETCH_POSTACDINSTRUMENT_DATA = 'FETCH_POSTACDINSTRUMENT_DATA';
export const POST_ACDINSTRUMENT_DATA = 'POST_ACDINSTRUMENT_DATA';

export const FETCH_POSTACDDEAL_DATA = 'FETCH_POSTACDDEAL_DATA';
export const POST_ACDDEAL_DATA = 'POST_ACDDEAL_DATA';

export const FETCH_PUTACD_DATA = 'FETCH_PUTACD_DATA';
export const PUT_ACD_DATA = 'PUT_ACD_DATA';
