export const FETCH_INSTRUMENT = 'FETCH_INSTRUMENT';
export const RECEIVE_INSTRUMENT = 'RECEIVE_INSTRUMENT';

export const FETCH_READ_CSV = 'FETCH_READ_CSV';
export const RECEIVE_READ_CSV = 'RECEIVE_READ_CSV';

export const FETCH_READ_PRICE = 'FETCH_READ_PRICE';
export const RECEIVE_READ_PRICE = 'RECEIVE_READ_PRICE';

export const FETCH_DEALING = 'FETCH_INSTRUMENT';
export const RECEIVE_DEALING = 'RECEIVE_INSTRUMENT';
